# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Machine Learning 101
author: Keaton Scheible
logo: images/tdg_logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: machine_learning_101.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/thatdspguy/machine_learning_101 
  path_to_book: "" 
  branch: development  

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  baseurl: "https://thatdspguy.com"